# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Zoneminder-InstallerScript
nav:
  - Home: 'index.md'
  - 'Installation Guide':
    - 'Alpine Linux': 'user-guide/Alpine.md'
    - 'Arch Linux': 'user-guide/Arch Linux.md'
    - 'Debian 12': 'user-guide/Debian12.md'
    - 'Debian 11': 'user-guide/Debian11.md'
    - 'Fedora': 'user-guide/Fedora.md'
    - 'OpenSUSE': 'user-guide/OpenSUSE.md'
    - 'Ubuntu': 'user-guide/Ubuntu.md'
  - About:
    - 'License': 'LICENSE.txt'
    - 'About': 'about.md'
repo_url: https://github.com/justaCasualCoder/Zoneminder-InstallerScript
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - bash
    palette:
      scheme: slate